# Web Server
# AMI: ami-013fffc873b1eaa1c
Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: |
          #! /bin/bash
          cat >~ /file <<EOF
          Hi, This is yogendra
          EOF 
      KeyName: yogendra-ec2-master
      ImageId: ami-013fffc873b1eaa1c
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: MyEC2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    GroupDescription: Allows SSH
    SecurityGroupIngress:
      - IpProtocol: ssh
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/22
    Tags:
      - Key: Name
        Value: "SSH Only"
  